import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\farhe\Desktop\archive (1)\data\forecast_data.csv")
df.head()
df.shape
#changing Data Type 
df['temp_c']=df['temp_c'].astype('int64')
df['wind_kph']=df['wind_kph'].astype('int64')
df['pressure_in']=df['pressure_in'].astype('int64')
df['feelslike_f']=df['feelslike_f'].astype('int64')
df['windchill_f']=df['windchill_f'].astype('int64')
df['heatindex_f']=df['heatindex_f'].astype('int64')
df['dewpoint_f']=df['dewpoint_f'].astype('int64')
df['vis_km']=df['vis_km'].astype('int64')
df['gust_kph']=df['gust_kph'].astype('int64')
df.info()
df.describe()
df.columns
#removing unwanted Columns from Dataset
df.drop('will_it_snow',axis=1,inplace=True)
df.drop('will_it_rain',axis=1,inplace=True)
df.drop('chance_of_rain',axis=1,inplace=True)
df.drop('chance_of_snow',axis=1,inplace=True)
df.drop('time_epoch',axis=1,inplace=True)
df.drop('temp_f',axis=1,inplace=True)
df.drop('condition',axis=1,inplace=True)
df.drop('wind_mph',axis=1,inplace=True)
df.drop('wind_kph',axis=1,inplace=True)
df.drop('wind_dir',axis=1,inplace=True)
df.drop('wind_degree',axis=1,inplace=True)
df.drop('pressure_mb',axis=1,inplace=True)
df.drop('pressure_in',axis=1,inplace=True)
df.drop('precip_mm',axis=1,inplace=True)
df.drop('precip_in',axis=1,inplace=True)
df.drop('feelslike_c',axis=1,inplace=True)
df.drop('feelslike_f',axis=1,inplace=True)
df.drop('windchill_c',axis=1,inplace=True)
df.drop('windchill_f',axis=1,inplace=True)
df.drop('heatindex_f',axis=1,inplace=True)
df.drop('dewpoint_f',axis=1,inplace=True)
df.drop('vis_miles',axis=1,inplace=True)
df.drop('gust_mph',axis=1,inplace=True)
df.drop('gust_kph',axis=1,inplace=True)
df.drop('city',axis=1,inplace=True)
df.columns
df.shape
df.head()
df.isnull().sum()
#Graph Representation by Matplotlib
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['temp_c'])
plt.title('Distribution of Temperature State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Temperature in Celsius',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Graph plot 2
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['humidity'],color='yellow')
plt.title('Distribution Of Humidity State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Humidity',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Graph plot 3
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['cloud'],color='brown')
plt.title('Distribution Of Cloud State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Cloud',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Graph plot 4
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['heatindex_c'],color='r')
plt.title('Level of Headt State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Heat',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Graph plot 5
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['dewpoint_c'],color='orange')
plt.title('Level of Coldness State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Level Of Cold',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Graph plot 6
plt.figure(figsize=(20,4))
plt.bar(df['state'],df['vis_km'],color='pink')
plt.title('Visibility in Kilometers State Wise',fontsize=15)
plt.xlabel('State',fontsize=10)
plt.ylabel('Visibility in Kilometers',fontsize=10)
plt.xticks(rotation=45)
plt.show()
#Rename Columns name
df.rename(columns={'temp_c':'Temperature','is_day':'Day','cloud':'Cloud','heatindex_c':'Heat','dewpoint_c':'Coldness','vis_km':'Distance'},inplace=True)
df.columns
df=df[['Temperature', 'Day', 'humidity', 'Cloud', 'Heat', 'Coldness','Distance']]
df.describe()
#Graph plot 7, Histgram plot
plt.figure(figsize=(10,4))
plt.hist(df)
plt.legend(labels=df)
plt.title('Wheather Component')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()
